Mesd\NotificationBundle\Entity\Template:
    type:            entity
    table:           notify_template
    repositoryClass: Mesd\NotificationBundle\Entity\TemplateRepository
    fields:
        id:
            id:       true
            type:     integer
            unsigned: false
            nullable: false
            generator:
                strategy: AUTO
            sequenceGenerator:
                sequenceName: notify_template_id_seq
                initialValue: 1
        shortName:
            column:   short_name
            type:     string
            length:   16
            nullable: false
            unique:   true
        longName:
            column:   long_name
            type:     string
            length:   64
            nullable: true
            unique:   false
        description:
            column:   description
            type:     text
            nullable: true
            unique:   false
        body:
            column:   body
            type:     text
            nullable: false
            unique:   false
    lifecycleCallbacks: {  }
