<?php

namespace Mesd\NotificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationParameterRepository extends EntityRepository
{
}
