<?php

namespace Mesd\NotificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParameterTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterTypeRepository extends EntityRepository
{
}
